export const countriesList = [
  { id: 1, name: "Canada", code: "CA", region: 1, country_code: 1 },
  { id: 2, name: "United States", code: "US", region: 1, country_code: 1 },
  { id: 3, name: "Mexico", code: "MX", region: 1, country_code: 52 },
  { id: 4, name: "Guatemala", code: "GT", region: 1, country_code: 502 },
  { id: 5, name: "Belize", code: "BZ", region: 1, country_code: 501 },
  { id: 6, name: "El Salvador", code: "SV", region: 1, country_code: 503 },
  { id: 7, name: "Honduras", code: "HN", region: 1, country_code: 504 },
  { id: 8, name: "Nicaragua", code: "NI", region: 1, country_code: 505 },
  { id: 9, name: "Costa Rica", code: "CR", region: 1, country_code: 506 },
  { id: 10, name: "Panama", code: "PA", region: 1, country_code: 507 },
  { id: 11, name: "Bahamas", code: "BS", region: 1, country_code: 1 },
  { id: 12, name: "Cuba", code: "CU", region: 1, country_code: 53 },
  { id: 13, name: "Jamaica", code: "JM", region: 1, country_code: 1 },
  { id: 14, name: "Haiti", code: "HT", region: 1, country_code: 509 },
  {
    id: 15,
    name: "Dominican Republic",
    code: "DO",
    region: 1,
    country_code: 1,
  },
  {
    id: 16,
    name: "Saint Kitts and Nevis",
    code: "KN",
    region: 1,
    country_code: 1,
  },
  {
    id: 17,
    name: "Antigua and Barbuda",
    code: "AG",
    region: 1,
    country_code: 1,
  },
  { id: 18, name: "Saint Lucia", code: "LC", region: 1, country_code: 1 },
  {
    id: 19,
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    region: 1,
    country_code: 1,
  },
  { id: 20, name: "Barbados", code: "BB", region: 1, country_code: 1 },
  { id: 21, name: "Grenada", code: "GD", region: 1, country_code: 1 },
  {
    id: 22,
    name: "Trinidad and Tobago",
    code: "TT",
    region: 1,
    country_code: 1,
  },
  { id: 23, name: "Albania", code: "AL", region: 2, country_code: 355 },
  { id: 24, name: "Andorra", code: "AD", region: 2, country_code: 376 },
  { id: 25, name: "Armenia", code: "AM", region: 2, country_code: 374 },
  { id: 26, name: "Austria", code: "AT", region: 2, country_code: 43 },
  { id: 27, name: "Azerbaijan", code: "AZ", region: 2, country_code: 994 },
  { id: 28, name: "Belarus", code: "BY", region: 2, country_code: 375 },
  { id: 29, name: "Belgium", code: "BE", region: 2, country_code: 32 },
  {
    id: 30,
    name: "Bosnia and Herzegovina",
    code: "BA",
    region: 2,
    country_code: 387,
  },
  { id: 31, name: "Bulgaria", code: "BG", region: 2, country_code: 359 },
  { id: 32, name: "Croatia", code: "HR", region: 2, country_code: 385 },
  { id: 33, name: "Cyprus", code: "CY", region: 2, country_code: 357 },
  { id: 34, name: "Czech Republic", code: "CZ", region: 2, country_code: 420 },
  { id: 35, name: "Denmark", code: "DK", region: 2, country_code: 45 },
  { id: 36, name: "Estonia", code: "EE", region: 2, country_code: 372 },
  { id: 37, name: "Finland", code: "FI", region: 2, country_code: 358 },
  { id: 38, name: "France", code: "FR", region: 2, country_code: 33 },
  { id: 39, name: "Georgia", code: "GE", region: 2, country_code: 995 },
  { id: 40, name: "Germany", code: "DE", region: 2, country_code: 49 },
  { id: 41, name: "Greece", code: "GR", region: 2, country_code: 30 },
  { id: 42, name: "Hungary", code: "HU", region: 2, country_code: 36 },
  { id: 43, name: "Iceland", code: "IS", region: 2, country_code: 354 },
  { id: 44, name: "Ireland", code: "IE", region: 2, country_code: 353 },
  { id: 45, name: "Italy", code: "IT", region: 2, country_code: 39 },
  { id: 47, name: "Kosovo", code: "XK", region: 2, country_code: 383 },
  { id: 48, name: "Latvia", code: "LV", region: 2, country_code: 371 },
  { id: 49, name: "Liechtenstein", code: "LI", region: 2, country_code: 423 },
  { id: 50, name: "Lithuania", code: "LT", region: 2, country_code: 370 },
  { id: 51, name: "Luxembourg", code: "LU", region: 2, country_code: 352 },
  { id: 52, name: "Malta", code: "MT", region: 2, country_code: 356 },
  { id: 53, name: "Moldova", code: "MD", region: 2, country_code: 373 },
  { id: 54, name: "Monaco", code: "MC", region: 2, country_code: 377 },
  { id: 55, name: "Montenegro", code: "MNE", region: 2, country_code: 382 },
  { id: 56, name: "Netherlands", code: "NL", region: 2, country_code: 31 },
  { id: 57, name: "North Macedonia", code: "MK", region: 2, country_code: 389 },
  { id: 58, name: "Norway", code: "NO", region: 2, country_code: 47 },
  { id: 59, name: "Poland", code: "PL", region: 2, country_code: 48 },
  { id: 60, name: "Portugal", code: "PT", region: 2, country_code: 351 },
  { id: 61, name: "Romania", code: "RO", region: 2, country_code: 40 },
  { id: 62, name: "Russia", code: "RU", region: 2, country_code: 7 },
  { id: 63, name: "San Marino", code: "SM", region: 2, country_code: 378 },
  { id: 64, name: "Serbia", code: "RS", region: 2, country_code: 381 },
  { id: 65, name: "Slovakia", code: "SK", region: 2, country_code: 421 },
  { id: 66, name: "Slovenia", code: "SI", region: 2, country_code: 386 },
  { id: 67, name: "Spain", code: "ES", region: 2, country_code: 34 },
  { id: 68, name: "Sweden", code: "SE", region: 2, country_code: 46 },
  { id: 69, name: "Switzerland", code: "CH", region: 2, country_code: 41 },
  { id: 70, name: "Turkey", code: "TR", region: 2, country_code: 90 },
  { id: 71, name: "Ukraine", code: "UA", region: 2, country_code: 380 },
  { id: 72, name: "United Kingdom", code: "GB", region: 2, country_code: 44 },
  { id: 73, name: "Vatican City", code: "VA", region: 2, country_code: 39 },
  { id: 74, name: "Afghanistan", code: "AF", region: 3, country_code: 93 },
  { id: 75, name: "Bangladesh", code: "BD", region: 3, country_code: 880 },
  { id: 76, name: "Bhutan", code: "BT", region: 3, country_code: 975 },
  { id: 77, name: "Brunei", code: "BN", region: 3, country_code: 673 },
  { id: 78, name: "Cambodia", code: "KH", region: 3, country_code: 855 },
  { id: 79, name: "China", code: "CN", region: 3, country_code: 86 },
  { id: 80, name: "East Timor", code: "TL", region: 3, country_code: 670 },
  { id: 81, name: "India", code: "IN", region: 3, country_code: 91 },
  { id: 82, name: "Indonesia", code: "ID", region: 3, country_code: 62 },
  { id: 83, name: "Japan", code: "JP", region: 3, country_code: 81 },
  { id: 84, name: "Kazakhstan", code: "KZ", region: 3, country_code: 7 },
  { id: 85, name: "Kyrgyzstan", code: "KG", region: 3, country_code: 996 },
  { id: 86, name: "Laos", code: "LA", region: 3, country_code: 856 },
  { id: 87, name: "Malaysia", code: "MY", region: 3, country_code: 60 },
  { id: 88, name: "Maldives", code: "MV", region: 3, country_code: 960 },
  { id: 89, name: "Mongolia", code: "MN", region: 3, country_code: 976 },
  { id: 90, name: "Myanmar", code: "MM", region: 3, country_code: 95 },
  { id: 91, name: "Nepal", code: "NP", region: 3, country_code: 977 },
  { id: 92, name: "North Korea", code: "KP", region: 3, country_code: 850 },
  { id: 93, name: "Pakistan", code: "PK", region: 3, country_code: 92 },
  { id: 94, name: "Philippines", code: "PH", region: 3, country_code: 63 },
  { id: 95, name: "Singapore", code: "SG", region: 3, country_code: 65 },
  { id: 96, name: "South Korea", code: "KR", region: 3, country_code: 82 },
  { id: 97, name: "Sri Lanka", code: "LK", region: 3, country_code: 94 },
  { id: 98, name: "Tajikistan", code: "TJ", region: 3, country_code: 992 },
  { id: 99, name: "Thailand", code: "TH", region: 3, country_code: 66 },
  { id: 100, name: "Turkmenistan", code: "TM", region: 3, country_code: 993 },
  { id: 101, name: "Uzbekistan", code: "UZ", region: 3, country_code: 998 },
  { id: 102, name: "Vietnam", code: "VN", region: 3, country_code: 84 },
  { id: 105, name: "Egypt", code: "EG", region: 4, country_code: 20 },
  { id: 106, name: "Iran", code: "IR", region: 4, country_code: 98 },
  { id: 107, name: "Iraq", code: "IQ", region: 4, country_code: 964 },
  { id: 108, name: "Israel", code: "IL", region: 4, country_code: 972 },
  { id: 109, name: "Jordan", code: "JO", region: 4, country_code: 962 },
  { id: 111, name: "Lebanon", code: "LB", region: 4, country_code: 961 },
  { id: 113, name: "Palestine", code: "PS", region: 4, country_code: 970 },
  { id: 115, name: "Saudi Arabia", code: "SA", region: 4, country_code: 966 },
  { id: 116, name: "Syria", code: "SY", region: 4, country_code: 963 },
  {
    id: 117,
    name: "United Arab Emirates",
    code: "AE",
    region: 4,
    country_code: 971,
  },
  { id: 118, name: "Yemen", code: "YE", region: 4, country_code: 967 },
  { id: 119, name: "Bahrain", code: "BH", region: 5, country_code: 973 },
  { id: 121, name: "Kuwait", code: "KW", region: 5, country_code: 965 },
  { id: 122, name: "Oman", code: "OM", region: 5, country_code: 968 },
  { id: 123, name: "Qatar", code: "QA", region: 5, country_code: 974 },
  { id: 126, name: "Argentina", code: "AR", region: 6, country_code: 54 },
  { id: 127, name: "Bolivia", code: "BO", region: 6, country_code: 591 },
  { id: 128, name: "Brazil", code: "BR", region: 6, country_code: 55 },
  { id: 129, name: "Chile", code: "CL", region: 6, country_code: 56 },
  { id: 130, name: "Colombia", code: "CO", region: 6, country_code: 57 },
  { id: 131, name: "Ecuador", code: "EC", region: 6, country_code: 593 },
  { id: 132, name: "Guyana", code: "GY", region: 6, country_code: 592 },
  { id: 133, name: "Paraguay", code: "PY", region: 6, country_code: 595 },
  { id: 134, name: "Peru", code: "PE", region: 6, country_code: 51 },
  { id: 135, name: "Suriname", code: "SR", region: 6, country_code: 597 },
  { id: 136, name: "Uruguay", code: "UY", region: 6, country_code: 598 },
  { id: 137, name: "Venezuela", code: "VE", region: 6, country_code: 58 },
  { id: 138, name: "Algeria", code: "DZ", region: 7, country_code: 213 },
  { id: 139, name: "Angola", code: "AO", region: 7, country_code: 244 },
  { id: 140, name: "Benin", code: "BJ", region: 7, country_code: 229 },
  { id: 141, name: "Botswana", code: "BW", region: 7, country_code: 267 },
  { id: 142, name: "Burkina Faso", code: "BF", region: 7, country_code: 226 },
  { id: 143, name: "Burundi", code: "BI", region: 7, country_code: 257 },
  { id: 144, name: "Cabo Verde", code: "CV", region: 7, country_code: 238 },
  { id: 145, name: "Cameroon", code: "CM", region: 7, country_code: 237 },
  {
    id: 146,
    name: "Central African Republic",
    code: "CF",
    region: 7,
    country_code: 236,
  },
  { id: 147, name: "Chad", code: "TD", region: 7, country_code: 235 },
  { id: 148, name: "Comoros", code: "KM", region: 7, country_code: 269 },
  {
    id: 149,
    name: "Democratic Republic of the Congo",
    code: "CD",
    region: 7,
    country_code: 243,
  },
  { id: 150, name: "Djibouti", code: "DJ", region: 7, country_code: 253 },
  {
    id: 152,
    name: "Equatorial Guinea",
    code: "GQ",
    region: 7,
    country_code: 240,
  },
  { id: 153, name: "Eritrea", code: "ER", region: 7, country_code: 291 },
  { id: 154, name: "Eswatini", code: "SZ", region: 7, country_code: 268 },
  { id: 155, name: "Ethiopia", code: "ET", region: 7, country_code: 251 },
  { id: 156, name: "Gabon", code: "GA", region: 7, country_code: 241 },
  { id: 157, name: "Gambia", code: "GM", region: 7, country_code: 220 },
  { id: 158, name: "Ghana", code: "GH", region: 7, country_code: 233 },
  { id: 159, name: "Guinea", code: "GN", region: 7, country_code: 224 },
  { id: 160, name: "Guinea-Bissau", code: "GW", region: 7, country_code: 245 },
  { id: 161, name: "Ivory Coast", code: "CI", region: 7, country_code: 225 },
  { id: 162, name: "Kenya", code: "KE", region: 7, country_code: 254 },
  { id: 163, name: "Lesotho", code: "LS", region: 7, country_code: 266 },
  { id: 164, name: "Liberia", code: "LR", region: 7, country_code: 231 },
  { id: 165, name: "Libya", code: "LY", region: 7, country_code: 218 },
  { id: 166, name: "Madagascar", code: "MG", region: 7, country_code: 261 },
  { id: 167, name: "Malawi", code: "MW", region: 7, country_code: 265 },
  { id: 168, name: "Mali", code: "ML", region: 7, country_code: 223 },
  { id: 169, name: "Mauritania", code: "MR", region: 7, country_code: 222 },
  { id: 170, name: "Mauritius", code: "MU", region: 7, country_code: 230 },
  { id: 171, name: "Morocco", code: "MA", region: 7, country_code: 212 },
  { id: 172, name: "Mozambique", code: "MZ", region: 7, country_code: 258 },
  { id: 173, name: "Namibia", code: "NA", region: 7, country_code: 264 },
  { id: 174, name: "Niger", code: "NE", region: 7, country_code: 227 },
  { id: 175, name: "Nigeria", code: "NG", region: 7, country_code: 234 },
  {
    id: 176,
    name: "Republic of the Congo",
    code: "CG",
    region: 7,
    country_code: 242,
  },
  { id: 177, name: "Rwanda", code: "RW", region: 7, country_code: 250 },
  {
    id: 178,
    name: "S\u00e3o Tom\u00e9 and Pr\u00edncipe",
    code: "ST",
    region: 7,
    country_code: 239,
  },
  { id: 179, name: "Senegal", code: "SN", region: 7, country_code: 221 },
  { id: 180, name: "Seychelles", code: "SC", region: 7, country_code: 248 },
  { id: 181, name: "Sierra Leone", code: "SL", region: 7, country_code: 232 },
  { id: 182, name: "Somalia", code: "SO", region: 7, country_code: 252 },
  { id: 183, name: "South Africa", code: "ZA", region: 7, country_code: 27 },
  { id: 184, name: "South Sudan", code: "SS", region: 7, country_code: 211 },
  { id: 185, name: "Sudan", code: "SD", region: 7, country_code: 249 },
  { id: 186, name: "Tanzania", code: "TZ", region: 7, country_code: 255 },
  { id: 187, name: "Togo", code: "TG", region: 7, country_code: 228 },
  { id: 188, name: "Tunisia", code: "TN", region: 7, country_code: 216 },
  { id: 189, name: "Uganda", code: "UG", region: 7, country_code: 256 },
  { id: 190, name: "Zambia", code: "ZM", region: 7, country_code: 260 },
  { id: 191, name: "Zimbabwe", code: "ZW", region: 7, country_code: 263 },
  { id: 192, name: "Australia", code: "AU", region: 8, country_code: 61 },
  { id: 193, name: "Fiji", code: "FJ", region: 8, country_code: 679 },
  { id: 194, name: "Kiribati", code: "KI", region: 8, country_code: 686 },
  {
    id: 195,
    name: "Marshall Islands",
    code: "MH",
    region: 8,
    country_code: 692,
  },
  { id: 196, name: "Micronesia", code: "FM", region: 8, country_code: 691 },
  { id: 197, name: "Nauru", code: "NR", region: 8, country_code: 674 },
  { id: 198, name: "New Zealand", code: "NZ", region: 8, country_code: 64 },
  { id: 199, name: "Palau", code: "PW", region: 8, country_code: 680 },
  {
    id: 200,
    name: "Papua New Guinea",
    code: "PG",
    region: 8,
    country_code: 675,
  },
  { id: 201, name: "Samoa", code: "WS", region: 8, country_code: 685 },
  {
    id: 202,
    name: "Solomon Islands",
    code: "SB",
    region: 8,
    country_code: 677,
  },
  { id: 203, name: "Tonga", code: "TO", region: 8, country_code: 676 },
  { id: 204, name: "Tuvalu", code: "TV", region: 8, country_code: 688 },
  { id: 205, name: "Vanuatu", code: "VU", region: 8, country_code: 678 },
  { id: 206, name: "Tokelau", code: "TK", region: 7, country_code: 690 },
  { id: 207, name: "Guernsey", code: "GG", region: 7, country_code: 44 - 1481 },
  { id: 208, name: "Hong Kong", code: "HK", region: 7, country_code: 852 },
];
export const TerritoryList = [
  {
    id: 1,
    name: "North America",
    code: "NA",
    value: "1t",
    view: "North America",
    type: "Territory",
  },
  {
    id: 2,
    name: "Europe",
    code: "EU",
    value: "2t",
    view: "Europe",
    type: "Territory",
  },
  {
    id: 3,
    name: "Asia",
    code: "AS",
    value: "3t",
    view: "Asia",
    type: "Territory",
  },
  {
    id: 4,
    name: "Middle East",
    code: "ME",
    value: "4t",
    view: "Middle East",
    type: "Territory",
  },
  {
    id: 5,
    name: "Gulf Countries",
    code: "GC",
    value: "5t",
    view: "Gulf Countries",
    type: "Territory",
  },
  {
    id: 6,
    name: "South America",
    code: "SA",
    value: "6t",
    view: "South America",
    type: "Territory",
  },
  {
    id: 7,
    name: "Africa",
    code: "AF",
    value: "7t",
    view: "Africa",
    type: "Territory",
  },
  {
    id: 8,
    name: "Australia and Oceania",
    code: "AO",
    value: "8t",
    view: "Australia and Oceania",
    type: "Territory",
  },
];
